Repository 404-DriverNotFound/backend-b, pull requests merged in 2021-09, with the labels that each got.

#76 Fix: static 파일 제공 방식 변경(#75)
  src/app.module.ts
  src/files/files.controller.ts
  src/files/files.module.ts
  src/main.ts
Labels: bug

#77 Feat: mute 기능 추가(#43)
  .env.stage.dev
  .env.stage.prod
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/entities/membership.entity.ts
Labels: enhancement

#78 Fix: 소켓 연결 상태로 온라인 오프라인되도록 수정(#34)
  src/events/events.gateway.ts
  src/events/events.module.ts
Labels: enhancement

#79 Fix: `join` event를 특정 채널만 join하는 이벤트로 수정
  src/events/events.gateway.ts
Labels: enhancement

#82 Fix: 유저를 추가하는 API에서 에러 메시지 수정
  src/channels/channels.service.ts
Labels: bug

#81 Fix: enable2FA를 boolean으로 변경
  src/app.service.ts
  src/main.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: bug

#83 Fix: mute 로직 수정
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/entities/membership.entity.ts
Labels: enhancement

#84 Refactor: mute API 예외 케이스 수정
  src/channels/channels.service.ts
Labels: enhancement

#85 Refactor: MemberRole API 예외 케이스 수정
  src/channels/channels.service.ts
Labels: enhancement

#87 Fix: 특정채널에서 퇴장하는 API를 memberName parameter를 받도록 수정
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
Labels: bug, enhancement

#90 Feat 관전 가능방 가져오는 API 추가
  src/matches/dto/get-matches-filter.dto.ts
  src/matches/dto/get-spectating-filter.dto.ts
  src/matches/dto/pagination-match-filter.dto.ts
  src/matches/matches.controller.ts
  src/matches/matches.repository.ts
  src/matches/matches.service.ts
Labels: enhancement

#93 Feat: 업적 기능 추가
  Dockerfile
  package.json
  src/achievements/achievements.controller.ts
  src/achievements/achievements.module.ts
  src/achievements/achievements.seeder.ts
  src/achievements/achievements.service.ts
  src/achievements/constants/achievement-description.enum.ts
  src/achievements/constants/achievement-name.enum.ts
  src/achievements/entities/achievement.entity.ts
  src/achievements/entities/user-achievement.entity.ts
  src/achievements/repositories/achievement.repository.ts
  src/achievements/repositories/user-achievement.repository.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/guards/second-factor-authenticated.guard.ts
  src/auth/session.serializer.ts
  src/auth/strategies/ft.strategy.ts
  src/channels/channels.controller.ts
  src/channels/channels.module.ts
  src/channels/channels.service.ts
  src/channels/entities/chat.entity.ts
  src/channels/entities/membership.entity.ts
  src/channels/repositories/channels.repository.ts
  src/dms/dm.entity.ts
  src/dms/dms.controller.ts
  src/dms/dms.module.ts
  src/dms/dms.repository.ts
  src/dms/dms.service.ts
  src/events/events.gateway.ts
  src/events/events.module.ts
  src/friendships/friendship.entity.ts
  src/friendships/friendships.controller.ts
  src/friendships/friendships.module.ts
  src/friendships/friendships.repository.ts
  src/friendships/friendships.service.ts
  src/seeder.ts
  src/users/constants/multer-options.ts
  src/users/constants/user-status.enum.ts
  src/users/entities/user.entity.ts
  src/users/get-user.decorator.ts
  src/users/repositories/users.repository.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
  start.sh
  yarn.lock
Labels: enhancement

#92 Fix: black 명칭을 block으로 수정
  src/app.service.ts
  src/friendships/friendships.controller.ts
  src/friendships/friendships.repository.ts
  src/friendships/friendships.service.ts
Labels: bug

#95 Fix: GameMode 추가 (#94)
  src/matches/constants/match-game-mode.enum.ts
  src/matches/dto/create-match.dto.ts
  src/matches/match.entity.ts
  src/matches/matches.controller.ts
  src/matches/matches.service.ts
Labels: enhancement

#97 Fix: seeder에 User와 관련된 repository 추가
  src/seeder.ts
Labels: bug

#99 Fix: `PATCH` `/users/me` API에서 enable2FA 오작동 수정
  src/users/repositories/users.repository.ts
  src/users/users.controller.ts
Labels: bug

#102 Feat: GET /matches/{name} API 추가 (#101)
  src/matches/dto/create-match.dto.ts
  src/matches/dto/get-matches-filter.dto.ts
  src/matches/dto/get-matches-info-filter.dto.ts
  src/matches/dto/get-spectating-filter.dto.ts
  src/matches/matches.controller.ts
  src/matches/matches.repository.ts
  src/matches/matches.service.ts
Labels: enhancement

#104 Feat: 특정 유저의 업적 목록을 가져오는 API 추가
  src/achievements/achievements.controller.ts
  src/achievements/achievements.module.ts
  src/achievements/achievements.service.ts
  src/achievements/constants/achievement-name.enum.ts
  src/achievements/entities/achievement.entity.ts
  src/achievements/repositories/achievement.repository.ts
  src/app.module.ts
  src/auth/auth.module.ts
  src/channels/channels.module.ts
  src/dms/dms.module.ts
  src/friendships/friendships.module.ts
  src/friendships/friendships.service.ts
  src/matches/matches.module.ts
  src/seeder.ts
  src/seeders/achievements.seeder.ts
  src/users/constants/achievement-description.enum.ts
  src/users/constants/achievement-name.enum.ts
  src/users/entities/achievement.entity.ts
  src/users/entities/user-achievement.entity.ts
  src/users/entities/user.entity.ts
  src/users/repositories/achievement.repository.ts
  src/users/repositories/user-achievement.repository.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement

#105 Feat: 게임 기능 추가
  package.json
  public/favicon.ico
  public/img/background001.png
  public/index.html
  public/wav/notification001.wav
  public/wav/pong001.wav
  src/app.module.ts
  src/events/events.gateway.ts
  src/events/events.module.ts
  src/events/events.service.ts
  src/events/games/classes/ball.class.ts
  src/events/games/classes/base.class.ts
  src/events/games/classes/countdown.class.ts
  src/events/games/classes/player.class.ts
  src/events/games/classes/point.class.ts
  src/events/games/classes/room.class.ts
  src/events/games/constants/SETTINGS.ts
  src/events/games/constants/collision-type.enum.ts
  src/events/games/constants/direction-to.enum.ts
  src/events/games/constants/game-status.enum.ts
  src/events/games/constants/key-code.enum.ts
  src/events/games/constants/player-position.enum.ts
  src/events/games/constants/quadrant.enum.ts
  src/events/games/dto/emit-data.dto.ts
  src/events/games/game-manager.service.ts
  src/events/games/interfaces/dynamic.interface.ts
  src/events/games/interfaces/rectangle.interface.ts
  src/events/games/interfaces/serve.interface.ts
  src/events/games/lobby-manager.service.ts
  src/events/games/room-manager.service.ts
  yarn.lock
Labels: enhancement

#107 Feat: 유저의 승, 패 정보 추가
  src/events/games/room-manager.service.ts
  src/users/entities/user.entity.ts
Labels: enhancement

#111 Refactor: matches API 수정
  src/app.module.ts
  src/auth/auth.module.ts
  src/channels/channels.module.ts
  src/dms/dms.module.ts
  src/friendships/friendships.module.ts
  src/matches/constants/match-result.enum.ts
  src/matches/dto/get-matches-count-filter.dto.ts
  src/matches/dto/get-matches-filter.dto.ts
  src/matches/dto/get-spectating-filter.dto.ts
  src/matches/dto/pagination-match-filter.dto.ts
  src/matches/match.entity.ts
  src/matches/matches.controller.ts
  src/matches/matches.repository.ts
  src/matches/matches.service.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement
